### ISSUE TITLE
when i run the demo,it has error:

### ISSUE THREAD

**Issue by betterhalfwzm** [knorth55/chainer-fcis#20]
[/home/iva/data/models/chainer/fcis_coco.npz] Checking md5 (689f9f01e7ee37f591b218e49c6686fb)
Traceback (most recent call last):
  File "demo.py", line 83, in <module>
    main()
  File "demo.py", line 67, in main
    min_drop_size, iter2=iter2)
  File "/home/iva/chainer-fcis/fcis/models/fcis_resnet101.py", line 227, in predict
    x, scale, iter2=iter2)
  File "/home/iva/chainer-fcis/fcis/models/fcis_resnet101.py", line 94, in __call__
    h, img_size, scale)
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/faster_rcnn/region_proposal_network.py", line 111, in __call__
    self.xp.array(self.anchor_base), self.feat_stride, hh, ww)
  File "/usr/local/lib/python2.7/dist-packages/chainercv/links/model/faster_rcnn/region_proposal_network.py", line 152, in _enumerate_shifted_anchor
    shift_y.ravel(), shift_x.ravel()), axis=1)
  File "/usr/local/lib/python2.7/dist-packages/cupy/manipulation/join.py", line 126, in stack
    'axis {} out of bounds [0, {})'.format(axis, x.ndim))
numpy.core._internal.AxisError: axis 1 out of bounds [0, 1)

**Comment by knorth55** [comment]
can you  tell me`chainer`, `cupy`,  `chainercv`  and `chainer-fcis`?
