### ISSUE TITLE
TypeError: Variables cannot be evaluated as Python bool.

### ISSUE THREAD

**Issue by Ctu-SiTuShenPeng** [knorth55/chainer-fcis#29]
Hi, I saw this forum: https://github.com/chainer/chainer/issues/7626
I want to ask what I encountered: TypeError: Variables cannot be evaluated as Python bool.
How did you solve this?

**Comment by knorth55** [comment]
if it is not related to this repo, i have no idea.
please tell me how to reproduce your error and paste all output of your program.

**Comment by Ctu-SiTuShenPeng** [comment]
I am following your project: https://github.com/knorth55/chainer-mask-rcnn
-------------------------------------------------- -------------------------------------------------- -----
The error message is:
Exception in main training loop: Variables cannot be evaluated as Python bool.
Traceback (most recent call last):
  File "C:\python38\Lib\site-packages\chainer\training\trainer.py", line 343, in run
    update()
  File "C:\python38\Lib\site-packages\chainer\training\updaters\standard_updater.py", line 240, in update
    self.update_core()
  File "C:\python38\Lib\site-packages\chainer\training\updaters\standard_updater.py", line 253, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "C:\python38\Lib\site-packages\chainer\optimizer.py", line 874, in update
    loss = lossfun(*args, **kwds)
  File ".\nets\mask_rcnn_train_chain.py", line 85, in __call__
    rpn_locs = F.concat(rpn_locs, axis=0)
  File "C:\python38\Lib\site-packages\chainer\functions\array\concat.py", line 108, in concat
    y, = Concat(axis).apply(xs)
  File "C:\python38\Lib\site-packages\chainer\function_node.py", line 267, in apply
    is_chainerx, in_data = _extract_apply_in_data(inputs)
  File "C:\python38\Lib\site-packages\chainer\function_node.py", line 1323, in _extract_apply_in_data
    if not inputs:
  File "C:\python38\Lib\site-packages\chainer\variable.py", line 1721, in __bool__
    raise TypeError(
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File ".\Ctu_MaskRCNN.py", line 159, in <module>
    ctu.train(TrainNum=150,learning_rate=0.001,ModelPath='result_Model')
  File ".\Ctu_MaskRCNN.py", line 154, in train
    trainer.run()
  File "C:\python38\Lib\site-packages\chainer\training\trainer.py", line 376, in run
    six.reraise(*exc_info)
  File "C:\python38\Lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\python38\Lib\site-packages\chainer\training\trainer.py", line 343, in run
    update()
  File "C:\python38\Lib\site-packages\chainer\training\updaters\standard_updater.py", line 240, in update
    self.update_core()
  File "C:\python38\Lib\site-packages\chainer\training\updaters\standard_updater.py", line 253, in update_core
    optimizer.update(loss_func, *in_arrays)
  File "C:\python38\Lib\site-packages\chainer\optimizer.py", line 874, in update
    loss = lossfun(*args, **kwds)
  File ".\nets\mask_rcnn_train_chain.py", line 85, in __call__
    rpn_locs = F.concat(rpn_locs, axis=0)
  File "C:\python38\Lib\site-packages\chainer\functions\array\concat.py", line 108, in concat
    y, = Concat(axis).apply(xs)
  File "C:\python38\Lib\site-packages\chainer\function_node.py", line 267, in apply
    is_chainerx, in_data = _extract_apply_in_data(inputs)
  File "C:\python38\Lib\site-packages\chainer\function_node.py", line 1323, in _extract_apply_in_data
    if not inputs:
  File "C:\python38\Lib\site-packages\chainer\variable.py", line 1721, in __bool__
    raise TypeError(
TypeError: Variables cannot be evaluated as Python bool.
-------------------------------------------------- -------------------------------------------------- -----
The version used is: python3.8 chainer7.8.1

**Comment by knorth55** [comment]
please use `wkentaro/chainer-mask-rcnn` and do not open the issue in different repo.

**Comment by knorth55** [comment]
move to https://github.com/wkentaro/chainer-mask-rcnn/issues/41
